### ISSUE TITLE
thats not using signed time-limited tokens and needs a database ^^

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [MarkusH/django-sshlogin#1]

**Comment by MarkusH** [comment]
Fair enough. An implementation based on https://docs.djangoproject.com/en/1.8/topics/signing/ should be even simpler.

**Comment by MarkusH** [comment]
An actual implementation could leverage [aaugustin/django-sesame](https://github.com/aaugustin/django-sesame)

**Comment by RonnyPfannschmidt** [comment]
closing this to get the open ticket out of my dashboard
